require('user.plugconfig.onedarkpro')
require('user.plugconfig.lualine')
require('user.plugconfig.bufferline')
require('user.plugconfig.nvimtree')
require('user.plugconfig.startify')
require('user.plugconfig.telescope')
require('user.plugconfig.hop')
